id: ironic_post_swift_key
version: '8.0'
handler: shell
actions:
  run: ruby /etc/puppet/modules/osnailyfacter/modular/astute/ironic_post_swift_key.rb
  update: ruby /etc/puppet/modules/osnailyfacter/modular/astute/ironic_post_swift_key.rb
