id: sync_time
version: '8.0'
handler: shell
actions:
  run: timeout -s9 40 ntpdate -u -v -s $(awk '/^server/ { if ($2 !~ /127\.127\.[0-9]+\.[0-9]+/)
    {ORS=" "; print $2}}' /etc/ntp.conf)
  update: timeout -s9 40 ntpdate -u -v -s $(awk '/^server/ { if ($2 !~ /127\.127\.[0-9]+\.[0-9]+/)
    {ORS=" "; print $2}}' /etc/ntp.conf)
