id: ceph_ready_check
version: '8.0'
handler: shell
actions:
  run: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_ready_check.rb
  update: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_ready_check.rb
